### ISSUE TITLE
Improve robustness of RLP codec in ipa-multipoint

### ISSUE THREAD

**Issue by thomas-quadratic** [hyperledger/besu-native#154]
Currently, there is no error handling for RLP encoding and decoding in the rust native lib ipa-multipoint.
The lib assumes correct inputs or crashes otherwise.
Although we have control over the inputs, it would be safer to implement proper error handling and propagation for RLP codec.
This means:

1. Catching codec errors on the rust side
2. Throwing appropriate Exception in the JVM

Tests should include bad inputs to test that exceptions are properly thrown.

**Comment by gfukushima** [comment]
I'm not sure I understood part of this issue. Are we're creating a issue here to add error handling on the rust side?

**Comment by thomas-quadratic** [comment]
Hi @gfukushima : after discussion on telegram, I think we should try to do without RLP encoding. If you are OK, we can close this Issue, especially that error handling has been added in a new PR.
