### ISSUE TITLE
EIP-2537: BLS updates for subgroups checks.

### ISSUE THREAD

**Issue by jflo** [hyperledger/besu-native#165]
The use of BLS curves has been amended to require a subgroup check for most operations:

https://eips.ethereum.org/EIPS/eip-2537#subgroup-checks

Advice from @shemnon 

https://github.com/ethereum/execution-spec-tests/pull/499 are the pending BLS tests, but you will want https://github.com/ethereum/execution-spec-tests/pull/511 in your local set so --traces can be turned on.

Here's my CLI I use.  Your directories of choice will differ.

fill --from=Prague --until=Prague -v tests/prague --evm-bin /Users/<username>/src/besu/build/install/besu/bin/evmtool  --t8n-dump-dir build/besu_eof --traces > build/besu_eof/res.txt

**Comment by marioevz** [comment]
We just merged https://github.com/ethereum/execution-spec-tests/pull/511 and rebased all Prague EIP tests including https://github.com/ethereum/execution-spec-tests/pull/499 on top of it so no need to do it manually anymore :+1:
