### ISSUE TITLE
Add linux arm64 support in Constantine build

### ISSUE THREAD

**Issue by garyschulte** [hyperledger/besu-native#198]
Initial support for Constantine in besu-native in #184 omitted building for linux-arm64.  Support for linux arm64 is mostly just a matter of getting nim installed in the CI build container for arm64, as the rest of the plumbing already exists.

```
choosenim-init: Error: Sorry, your platform (linux_arm64) is not supported by choosenim.
choosenim-init: Error: You will need to install Nim using an alternative method.
choosenim-init: Error: See the following link for more info: https://nim-lang.org/install.html
```

_Originally posted by @garyschulte in https://github.com/hyperledger/besu-native/issues/184#issuecomment-2287031271_

**Comment by garyschulte** [comment]
It appears that the mac support aarch64 and x86 are not getting included in the final artifact.  The build version for [0.9.4](https://hyperledger.jfrog.io/artifactory/besu-maven/org/hyperledger/besu/constantine/0.9.4/constantine-0.9.4.jar) only includes linux x86 libs:
```
     0 Tue Aug 13 23:09:30 PDT 2024 META-INF/
   246 Tue Aug 13 23:09:30 PDT 2024 META-INF/MANIFEST.MF
     0 Tue Aug 13 23:09:30 PDT 2024 org/
     0 Tue Aug 13 23:09:30 PDT 2024 org/hyperledger/
     0 Tue Aug 13 23:09:30 PDT 2024 org/hyperledger/besu/
     0 Tue Aug 13 23:09:30 PDT 2024 org/hyperledger/besu/nativelib/
     0 Tue Aug 13 23:09:30 PDT 2024 org/hyperledger/besu/nativelib/constantine/
  1939 Tue Aug 13 23:09:30 PDT 2024 org/hyperledger/besu/nativelib/constantine/LibConstantineEIP196.class
     0 Tue Aug 13 23:09:30 PDT 2024 lib/
     0 Tue Aug 13 23:09:30 PDT 2024 lib/linux-gnu-x86_64/
 16608 Tue Aug 13 23:09:30 PDT 2024 lib/linux-gnu-x86_64/libconstantineeip196.so
3116280 Tue Aug 13 23:09:30 PDT 2024 lib/linux-gnu-x86_64/libconstantine.so
```

**Comment by NickSneo** [comment]
> It appears that the mac support aarch64 and x86 are not getting included in the final artifact. The build version for [0.9.4](https://hyperledger.jfrog.io/artifactory/besu-maven/org/hyperledger/besu/constantine/0.9.4/constantine-0.9.4.jar) only includes linux x86 libs:
> 
> ```
>      0 Tue Aug 13 23:09:30 PDT 2024 META-INF/
>    246 Tue Aug 13 23:09:30 PDT 2024 META-INF/MANIFEST.MF
>      0 Tue Aug 13 23:09:30 PDT 2024 org/
>      0 Tue Aug 13 23:09:30 PDT 2024 org/hyperledger/
>      0 Tue Aug 13 23:09:30 PDT 2024 org/hyperledger/besu/
>      0 Tue Aug 13 23:09:30 PDT 2024 org/hyperledger/besu/nativelib/
>      0 Tue Aug 13 23:09:30 PDT 2024 org/hyperledger/besu/nativelib/constantine/
>   1939 Tue Aug 13 23:09:30 PDT 2024 org/hyperledger/besu/nativelib/constantine/LibConstantineEIP196.class
>      0 Tue Aug 13 23:09:30 PDT 2024 lib/
>      0 Tue Aug 13 23:09:30 PDT 2024 lib/linux-gnu-x86_64/
>  16608 Tue Aug 13 23:09:30 PDT 2024 lib/linux-gnu-x86_64/libconstantineeip196.so
> 3116280 Tue Aug 13 23:09:30 PDT 2024 lib/linux-gnu-x86_64/libconstantine.so
> ```

I think it was due to this line of code -

```
def osName = System.getProperty('os.name').toLowerCase()
def osArch = System.getProperty('os.arch')
def libDir

if (osName.contains('mac') && osArch.contains('aarch64')) {
    libDir = 'darwin-aarch64'
} else if (osName.contains('mac')) {
    libDir = 'darwin-x86-64'
} else if (osName.contains('linux') && osArch.contains('aarch64')) {
    libDir = 'linux-gnu-aarch64'
} else {
    libDir = 'linux-gnu-x86_64'
}

task libCopy(type: Copy) {
    from "build/${libDir}/lib/"
    into "build/resources/main/lib/${libDir}"
}
```
It just copying lib for that particular OS_TYPE, whereas we need to copy lib for all the OS_TYPE in build.gradle
