### ISSUE TITLE
Besu Artifactory

### ISSUE THREAD

**Issue by shemnon** [hyperledger/besu-native#29]
Can we get besu artifactory setup?  (hyperledger.jfrog.io).  The credentials requirement for github packages will be a problem based on user feedback via the chat forums.

Ideal setup: 
* a `besu` and `besu-snapshot` namespace (so we can keep snapshots segregated and have a tighter pruning policy) on hyperledger.jfrog.io
* a context in CircleCI containing the artifactory user and password /token that can be used to publish (ARTIFACTORY_USERNAME/ARTIFACTORY/PASSWORD or something similar).

**Comment by ryjones** [comment]
Your username is the as here. Log in here: https://hyperledger.jfrog.io/ui/packages

**Comment by shemnon** [comment]
Migration complete for besu-native.
